// Code generated by MockGen. DO NOT EDIT.
// Source: ./receive_order.go
//
// Generated by this command:
//
//	mockgen -destination=./../../mocks/usecases/receive_order_mock.go -source=./receive_order.go -package=mocks_usecases
//
// Package mocks_usecases is a generated GoMock package.
package mocks_usecases

import (
	context "context"
	reflect "reflect"

	dtos "github.com/Pos-Tech-Challenge-48/delivery-merchant-api/internal/dtos"
	gomock "go.uber.org/mock/gomock"
)

// MockReceiveOrderUseCase is a mock of ReceiveOrderUseCase interface.
type MockReceiveOrderUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockReceiveOrderUseCaseMockRecorder
}

// MockReceiveOrderUseCaseMockRecorder is the mock recorder for MockReceiveOrderUseCase.
type MockReceiveOrderUseCaseMockRecorder struct {
	mock *MockReceiveOrderUseCase
}

// NewMockReceiveOrderUseCase creates a new mock instance.
func NewMockReceiveOrderUseCase(ctrl *gomock.Controller) *MockReceiveOrderUseCase {
	mock := &MockReceiveOrderUseCase{ctrl: ctrl}
	mock.recorder = &MockReceiveOrderUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReceiveOrderUseCase) EXPECT() *MockReceiveOrderUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockReceiveOrderUseCase) Handle(ctx context.Context, input *dtos.ReceiveOrderDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockReceiveOrderUseCaseMockRecorder) Handle(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockReceiveOrderUseCase)(nil).Handle), ctx, input)
}
