name: ci-cd-flow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'

      - name: Get dependencies
        run: go mod tidy

      - name: Run tests with coverage
        run: |
          go test -coverprofile=coverage.out ./...
      
      - name: Check coverage
        run: |
          go tool cover -func=coverage.out | awk '/total:/ {print $3}' | sed 's/%//' | awk '{exit ($1 < 80)}'
        shell: bash

      - name: Generate Docker tag
        id: generate_tag
        run: |
          TAG=$(date +'%Y%m%d%H%M%S')
          echo "::set-output name=tag::$TAG"

      - name: Build Docker image
        run: |
          docker build -t delivery-merchant-api:${{ steps.generate_tag.outputs.tag }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag delivery-merchant-api:${{ steps.generate_tag.outputs.tag }} ${{ secrets.DOCKER_USERNAME }}/delivery-merchant-api:${{ steps.generate_tag.outputs.tag }}
          docker push ${{ secrets.DOCKER_USERNAME }}/delivery-merchant-api:${{ steps.generate_tag.outputs.tag }}

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v1

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1
        
      - name: Update kube config
        run: aws eks update-kubeconfig --name cluster-example --region us-east-1

      - name: Deploy to EKS
        run: |
          sed -i.bak "s|DOCKER_IMAGE|ffelipelimao/delivery-merchant-api:${{ steps.generate_tag.outputs.tag }}|g" k8s/deployment.yaml && \
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml